version: '3'

services:

  web:
    build: .
    restart: always
    ports:
     - "8008:8008"

    # Note: 'volumes' binds container directory /code to
    # host files at ., allowing flask reload
    volumes:
     - .:/code


    depends_on:
    - mongo
    env_file:
    - development.env

  mongo:
    image: mongo
    restart: always
    env_file:
      - development.env